{% set name = "skfolio" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e88723c34fe208563fe8376559f65be20eb3f6b5adc1864b63f2960143acaf1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy >=1.23.4
    - scipy >=1.8.0
    - pandas >=1.4.1
    - cvxpy >=1.4.1
    - scikit-learn >=1.3.2
    - joblib >=1.3.2
    - plotly >=5.15.0

test:
  imports:
    - skfolio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/skfolio/skfolio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for portfolio optimization built on top of scikit-learn
  description: Python library for portfolio optimization built on top of scikit-learn
  dev_url: https://github.com/skfolio/skfolio

extra:
  recipe-maintainers:
    - timkpaine
