{% set name = "skfolio" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74257ef7167f06fd4fc4d730367b357b210f485cc95a39878d85700e67df21a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - numpy >=1.23.4
    - scipy >=1.8.0
    - pandas >=1.4.1
    - cvxpy >=1.4.1
    - scikit-learn >=1.5.0
    - joblib >=1.3.2
    - plotly >=5.22.0

test:
  imports:
    - skfolio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/skfolio/skfolio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for portfolio optimization built on top of scikit-learn
  description: Python library for portfolio optimization built on top of scikit-learn
  dev_url: https://github.com/skfolio/skfolio

extra:
  recipe-maintainers:
    - timkpaine
