{% set name = "skfolio" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36eda20725331cb1896e788b34ad54a4921ff20a74a399b533508522747e171b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy >=1.23.4
    - scipy >=1.8.0
    - pandas >=1.4.1
    - cvxpy >=1.4.1
    - scikit-learn >=1.3.2
    - joblib >=1.3.2
    - plotly >=5.15.0

test:
  imports:
    - skfolio

about:
  home: https://github.com/skfolio/skfolio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for portfolio optimization built on top of scikit-learn
  description: Python library for portfolio optimization built on top of scikit-learn
  dev_url: https://github.com/skfolio/skfolio

extra:
  recipe-maintainers:
    - timkpaine
