{% set name = "skfolio" %}
{% set version = "0.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be1e27b1bb4cf4f074b9b5a92d31c76d5ef770cebc6a288970f83358a9a9efb1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.23.4
    - scipy >=1.8.0
    - pandas >=1.4.1
    - cvxpy >=1.4.1
    - scikit-learn >=1.5.0
    - joblib >=1.3.2
    - plotly >=5.22.0

test:
  imports:
    - skfolio
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/skfolio/skfolio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for portfolio optimization built on top of scikit-learn
  description: Python library for portfolio optimization built on top of scikit-learn
  dev_url: https://github.com/skfolio/skfolio

extra:
  recipe-maintainers:
    - timkpaine
